use crate::cache::EmbedderCacheKey;
use crate::cache_io::{hex_lower, unix_ms};
use crate::error::{EmbedError, EmbedResult};
use crate::types::EmbedderOutput;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CacheEntryRecord {
    pub(crate) path: PathBuf,
    pub(crate) byte_count: u64,
    pub(crate) last_accessed_unix_ms: u128,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct CachedEmbedderVector {
    pub(crate) key: EmbedderCacheKey,
    pub(crate) vector: Vec<f32>,
    pub(crate) precision_class: String,
    pub(crate) written_at_unix_ms: u128,
    pub(crate) last_accessed_unix_ms: u128,
    pub(crate) access_count: u64,
}

impl CachedEmbedderVector {
    pub(crate) fn from_output(key: EmbedderCacheKey, output: &EmbedderOutput) -> EmbedResult<Self> {
        output.validate()?;
        validate_output_matches_key(&key, output)?;
        let now = unix_ms()?;
        Ok(Self {
            key,
            vector: output.vector.clone(),
            precision_class: output.precision_class.clone(),
            written_at_unix_ms: now,
            last_accessed_unix_ms: now,
            access_count: 0,
        })
    }

    pub(crate) fn validate(&self) -> EmbedResult<()> {
        self.key.validate()?;
        if self.last_accessed_unix_ms < self.written_at_unix_ms {
            return Err(EmbedError::invalid(
                "CachedEmbedderVector.last_accessed_unix_ms",
                format!(
                    "last_accessed_unix_ms {} is before written_at_unix_ms {}",
                    self.last_accessed_unix_ms, self.written_at_unix_ms
                ),
                "delete the corrupt cache entry; access metadata must be monotonic",
            ));
        }
        if self.vector.len() != self.key.embedder.dimension() {
            return Err(EmbedError::invalid(
                "CachedEmbedderVector.vector",
                format!(
                    "{} cached vector dimension {}, expected {}",
                    self.key.embedder,
                    self.vector.len(),
                    self.key.embedder.dimension()
                ),
                "delete the corrupt cache entry and recompute it from the pinned model",
            ));
        }
        if !self.vector.iter().all(|value| value.is_finite()) {
            return Err(EmbedError::invalid(
                "CachedEmbedderVector.vector",
                "cached vector contains NaN or Inf",
                "delete the corrupt cache entry and inspect the model forward logs",
            ));
        }
        if self.precision_class.trim().is_empty() {
            return Err(EmbedError::invalid(
                "CachedEmbedderVector.precision_class",
                "precision_class is empty",
                "persist the concrete forward precision class with each cache row",
            ));
        }
        Ok(())
    }

    pub(crate) fn touch(&mut self) -> EmbedResult<()> {
        self.last_accessed_unix_ms = unix_ms()?;
        self.access_count = self.access_count.checked_add(1).ok_or_else(|| {
            EmbedError::invalid(
                "CachedEmbedderVector.access_count",
                "access_count overflowed u64",
                "clear the cache entry after verifying telemetry for pathological hot-key churn",
            )
        })?;
        self.validate()
    }

    pub(crate) fn into_output(self, source_id: String) -> EmbedResult<EmbedderOutput> {
        self.validate()?;
        let output = EmbedderOutput {
            embedder: self.key.embedder,
            source_id,
            vector: self.vector,
            model_version: self.key.model_version,
            precision_class: self.precision_class,
        };
        output.validate()?;
        Ok(output)
    }
}

pub fn chunk_sha256(text: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(text.as_bytes());
    hex_lower(hasher.finalize().as_slice())
}

fn validate_output_matches_key(key: &EmbedderCacheKey, output: &EmbedderOutput) -> EmbedResult<()> {
    if output.embedder != key.embedder {
        return Err(EmbedError::forward(
            key.embedder,
            format!(
                "cache output embedder mismatch: key={} output={}",
                key.embedder, output.embedder
            ),
            "write only outputs generated by the same embedder as the cache key",
        ));
    }
    if output.model_version != key.model_version {
        return Err(EmbedError::forward(
            key.embedder,
            format!(
                "cache output model_version mismatch: key={} output={}",
                key.model_version, output.model_version
            ),
            "write only outputs generated by the exact model version in the cache key",
        ));
    }
    Ok(())
}
