//! Canonical ME-JEPA RocksDB column-family names.
//!
//! This crate is intentionally dependency-free so ME-JEPA runtime, hygiene,
//! MCP, and training crates can share CF names without cycles or string drift.

pub const CF_MEJEPA_FISHER_SNAPSHOTS: &str = "CF_MEJEPA_FISHER_SNAPSHOTS";
pub const CF_MEJEPA_DRIFT_WINDOW: &str = "CF_MEJEPA_DRIFT_WINDOW";
pub const CF_MEJEPA_DRIFT_HISTORY: &str = "CF_MEJEPA_DRIFT_HISTORY";
pub const CF_MEJEPA_HEAL_REPORTS: &str = "CF_MEJEPA_HEAL_REPORTS";
pub const CF_MEJEPA_DISTILL_STEPS: &str = "CF_MEJEPA_DISTILL_STEPS";
pub const CF_MEJEPA_ACTIVE_POINTERS: &str = "CF_MEJEPA_ACTIVE_POINTERS";
pub const CF_MEJEPA_CALIBRATION_HISTORY: &str = "CF_MEJEPA_CALIBRATION_HISTORY";
// TASK-PY-G-066 — predictor-wide continual-backprop plasticity history.
pub const CF_MEJEPA_PLASTICITY_HISTORY: &str = "CF_MEJEPA_PLASTICITY_HISTORY";
pub const CF_MEJEPA_WEIGHT_BLOBS: &str = "CF_MEJEPA_WEIGHT_BLOBS";
pub const CF_MEJEPA_SHIFT_WATERMARK: &str = "CF_MEJEPA_SHIFT_WATERMARK";
pub const CF_MEJEPA_TRAIN_CERTS: &str = "CF_MEJEPA_TRAIN_CERTS";
pub const CF_MEJEPA_LIVE_PREDICTIONS: &str = "CF_MEJEPA_LIVE_PREDICTIONS";
// TASK-PY-G-056 — end-to-end live Claude Code session trace rows.
pub const CF_MEJEPA_LIVE_SESSION_TRACES: &str = "CF_MEJEPA_LIVE_SESSION_TRACES";
// TASK-FP-102 — durable file/function/AST/chunk prediction hierarchy rows.
pub const CF_MEJEPA_HIERARCHICAL_PREDICTIONS: &str = "CF_MEJEPA_HIERARCHICAL_PREDICTIONS";
// Historical name: live runtime code stores bincode CalibrationExample
// oracle-binding rows here. Corpus-generation JSON OracleVerdict rows live
// in the separate lowercase corpus store CF `mejepa_oracle_verdicts`.
pub const CF_MEJEPA_ORACLE_VERDICTS: &str = "CF_MEJEPA_ORACLE_VERDICTS";
// TASK-PY-G-069 — observed test outcomes bound back to live predictions.
pub const CF_MEJEPA_PREDICTION_VERIFICATIONS: &str = "CF_MEJEPA_PREDICTION_VERIFICATIONS";
// TASK-PY-G-045 — Q5 replay records comparing predicted consequences to
// observed durable shift-log reality.
pub const CF_MEJEPA_REALITY_IMPACT: &str = "CF_MEJEPA_REALITY_IMPACT";
// TASK-PY-G-013 — Q5 calibration rows over replayed reality-impact records.
pub const CF_MEJEPA_Q5_CALIBRATIONS: &str = "CF_MEJEPA_Q5_CALIBRATIONS";
// TASK-PY-G-041 — deterministic Q1 agent-claim reconciliation rows.
pub const CF_MEJEPA_CLAIM_RECONCILIATION: &str = "CF_MEJEPA_CLAIM_RECONCILIATION";
// TASK-PY-G-064 — per-project reality compile report rows.
pub const CF_MEJEPA_PROJECT_REPORTS: &str = "CF_MEJEPA_PROJECT_REPORTS";
// TASK-PY-G-072 — end-to-end reality-compiler stress harness rows.
pub const CF_MEJEPA_STRESS_RUNS: &str = "CF_MEJEPA_STRESS_RUNS";
// TASK-PY-G-071 — known-answer synthetic Python stress-corpus eval rows.
pub const CF_MEJEPA_SYNTHETIC_STRESS_RESULTS: &str = "CF_MEJEPA_SYNTHETIC_STRESS_RESULTS";
pub const CF_MEJEPA_PANELS: &str = "CF_MEJEPA_PANELS";
// BLINDSPOT-004 / #726 — variable-arity chunk graph rows; additive beside the
// existing flat 5,120-d panel rows until the PanelGraph predictor head ships.
pub const CF_MEJEPA_PANEL_GRAPHS: &str = "CF_MEJEPA_PANEL_GRAPHS";
// TASK-PY-G-111 — cross-panel Goodhart-defense observations and agreement rows.
pub const CF_MEJEPA_PANEL_B_OBSERVATIONS: &str = "CF_MEJEPA_PANEL_B_OBSERVATIONS";
pub const CF_MEJEPA_CROSS_PANEL_AGREEMENT: &str = "CF_MEJEPA_CROSS_PANEL_AGREEMENT";
// TASK-PY-G-119 — binary-leaf pathway trees, surfaced top-K pathways,
// and operator choices over Q1/Q2/Q5 consequences.
pub const CF_MEJEPA_PATHWAY_TREES: &str = "CF_MEJEPA_PATHWAY_TREES";
pub const CF_MEJEPA_SURFACED_PATHWAYS: &str = "CF_MEJEPA_SURFACED_PATHWAYS";
pub const CF_MEJEPA_OPERATOR_PATHWAY_CHOICES: &str = "CF_MEJEPA_OPERATOR_PATHWAY_CHOICES";
// TASK-PY-G-116 — SWE-bench Docker outcome ontology and test-phase vectors.
pub const CF_MEJEPA_DOCKER_OUTCOME_LABELS: &str = "CF_MEJEPA_DOCKER_OUTCOME_LABELS";

// Canonical runtime/hygiene mutation-corpus CF. The corpus-generation crate
// also has a distinct lowercase JSON source CF `mejepa_mutation_corpus`.
pub const CF_MEJEPA_MUTATION_CORPUS: &str = "CF_MEJEPA_MUTATION_CORPUS";
pub const CF_MEJEPA_LIVE_ATTEMPT_CORPUS: &str = "CF_MEJEPA_LIVE_ATTEMPT_CORPUS";
pub const CF_MEJEPA_PANEL_META: &str = "CF_MEJEPA_PANEL_META";
pub const CF_MEJEPA_QUOTA_STATE: &str = "CF_MEJEPA_QUOTA_STATE";
pub const CF_MEJEPA_WEIGHT_BLOBS_META: &str = "CF_MEJEPA_WEIGHT_BLOBS_META";
pub const CF_MEJEPA_WITNESS_CHAIN: &str = "CF_MEJEPA_WITNESS_CHAIN";
pub const CF_MEJEPA_WITNESS_SEGMENT_META: &str = "CF_MEJEPA_WITNESS_SEGMENT_META";
pub const CF_MEJEPA_PANEL_CACHE: &str = "CF_MEJEPA_PANEL_CACHE";
pub const CF_MEJEPA_PANEL_DISK_OVERFLOW: &str = "CF_MEJEPA_PANEL_DISK_OVERFLOW";
pub const CF_MEJEPA_AUX_SIGNALS_OVERRIDES: &str = "CF_MEJEPA_AUX_SIGNALS_OVERRIDES";
pub const CF_MEJEPA_GC_HISTORY: &str = "CF_MEJEPA_GC_HISTORY";
pub const CF_MEJEPA_EVAL_REPORTS: &str = "CF_MEJEPA_EVAL_REPORTS";
// TASK-PY-G-054 — weekly negative-action ablation falsifier reports.
pub const CF_MEJEPA_ABLATION_REPORTS: &str = "CF_MEJEPA_ABLATION_REPORTS";
pub const CF_MEJEPA_TASK_GRAPH: &str = "CF_MEJEPA_TASK_GRAPH";
pub const CF_MEJEPA_TASK_GRAPH_HISTORY: &str = "CF_MEJEPA_TASK_GRAPH_HISTORY";
pub const CF_MEJEPA_ACTIVE_LEARNING_QUEUE: &str = "CF_MEJEPA_ACTIVE_LEARNING_QUEUE";
pub const CF_MEJEPA_ACTIVE_LEARNING_LABELS: &str = "CF_MEJEPA_ACTIVE_LEARNING_LABELS";
pub const CF_MEJEPA_ACTIVE_LEARNING_EVICTIONS: &str = "CF_MEJEPA_ACTIVE_LEARNING_EVICTIONS";
pub const CF_MEJEPA_OOD_ESCALATIONS: &str = "CF_MEJEPA_OOD_ESCALATIONS";
// TASK-PY-G-057 — live-session OOD harvest rows and weekly OOD calibration reports.
pub const CF_MEJEPA_OOD_HARVEST: &str = "CF_MEJEPA_OOD_HARVEST";
pub const CF_MEJEPA_OOD_CALIBRATIONS: &str = "CF_MEJEPA_OOD_CALIBRATIONS";
// TASK-EK-006 — per-window compression-progress curiosity distributions.
pub const CF_MEJEPA_CURIOSITY_TELEMETRY: &str = "CF_MEJEPA_CURIOSITY_TELEMETRY";
pub const CF_MEJEPA_RESEARCH_QUESTIONS: &str = "CF_MEJEPA_RESEARCH_QUESTIONS";
pub const CF_MEJEPA_MODEL_PROMOTIONS: &str = "CF_MEJEPA_MODEL_PROMOTIONS";
pub const CF_MEJEPA_PRODUCTION_TELEMETRY: &str = "CF_MEJEPA_PRODUCTION_TELEMETRY";
pub const CF_MEJEPA_CONSTELLATION: &str = "CF_MEJEPA_CONSTELLATION";
pub const CF_MEJEPA_GUARD_DECISIONS: &str = "CF_MEJEPA_GUARD_DECISIONS";
pub const CF_MEJEPA_CONSTELLATION_REFRESH_REPORTS: &str = "CF_MEJEPA_CONSTELLATION_REFRESH_REPORTS";
pub const CF_MEJEPA_CONSTELLATION_REFRESH_LOG: &str = "CF_MEJEPA_CONSTELLATION_REFRESH_LOG";

// REQ-FLYWHEEL-10 — three new column families for the data flywheel.
//
// String values match the existing `CF_MEJEPA_*` upper-case convention so the
// "constant name == on-disk CF name" invariant continues to hold across the
// whole registry (the lower-case strings in TECH-FLYWHEEL.md §6 are spec
// illustrations only; the live mejepa-cf convention takes precedence).
pub const CF_MEJEPA_DDA_SIGNALS: &str = "CF_MEJEPA_DDA_SIGNALS";
// TASK-PY-G-043 — per-head DDA feature schema versions and slice maps.
pub const CF_MEJEPA_HEAD_PROJECTION_REGISTRY: &str = "CF_MEJEPA_HEAD_PROJECTION_REGISTRY";
pub const CF_MEJEPA_FAILURE_EXEMPLARS: &str = "CF_MEJEPA_FAILURE_EXEMPLARS";
pub const CF_MEJEPA_AGENT_FEEDBACK: &str = "CF_MEJEPA_AGENT_FEEDBACK";
pub const CF_MEJEPA_FLYWHEEL_JOB_RUNS: &str = "CF_MEJEPA_FLYWHEEL_JOB_RUNS";
// REQ-PREDICT-12 — operator override records, keyed by prediction_id.
pub const CF_MEJEPA_OPERATOR_OVERRIDES: &str = "CF_MEJEPA_OPERATOR_OVERRIDES";
// TASK-EK-014 — operator-contribution events, keyed by contribution_id.
pub const CF_MEJEPA_OPERATOR_CONTRIBUTIONS: &str = "CF_MEJEPA_OPERATOR_CONTRIBUTIONS";
// TASK-PREDICT-LABEL-012 — durable decisions for every attempted label transfer.
pub const CF_MEJEPA_LABEL_TRANSFER_DECISIONS: &str = "CF_MEJEPA_LABEL_TRANSFER_DECISIONS";
// TASK-FLYWHEEL-007 — fail-closed retry park-list records, keyed by prediction_id.
pub const CF_MEJEPA_PARK_LIST: &str = "CF_MEJEPA_PARK_LIST";
// TASK-PY-G-061 — cold constellation cells must abstain and emit durable metrics.
pub const CF_MEJEPA_COLD_CELL_METRICS: &str = "CF_MEJEPA_COLD_CELL_METRICS";
// TASK-RWD-208 / TASK-PY-G-074 — normalized mypy/pyright/ruff labels.
pub const CF_MEJEPA_STATIC_ANALYSIS_SIGNALS: &str = "CF_MEJEPA_STATIC_ANALYSIS_SIGNALS";
// FROZEN 2026-05-19: see futurebuild/05 §16.
// TASK-RWD-204 / TASK-PY-G-046 — normalized Bandit/Semgrep Q4 security labels.
pub const CF_MEJEPA_Q4_SECURITY_LABELS: &str = "CF_MEJEPA_Q4_SECURITY_LABELS";
// FROZEN 2026-05-19: see futurebuild/05 §16.
// TASK-PY-G-047 — normalized pytest-benchmark/cProfile Q4 perf labels.
pub const CF_MEJEPA_Q4_PERF_LABELS: &str = "CF_MEJEPA_Q4_PERF_LABELS";
// FROZEN 2026-05-19: see futurebuild/05 §16.
// TASK-PY-G-048 — normalized Python accuracy/data-metric Q4 labels.
pub const CF_MEJEPA_Q4_ACCURACY_LABELS: &str = "CF_MEJEPA_Q4_ACCURACY_LABELS";
// FROZEN 2026-05-19: see futurebuild/05 §16.
// TASK-PY-G-049 — normalized Python CI/dependency/wheel-size Q4 cost labels.
pub const CF_MEJEPA_Q4_COST_LABELS: &str = "CF_MEJEPA_Q4_COST_LABELS";
// FROZEN 2026-05-19: see futurebuild/05 §16.
// TASK-PY-G-050 — normalized agent-prose / oracle-outcome Q4 reasoning labels.
pub const CF_MEJEPA_Q4_REASONING_LABELS: &str = "CF_MEJEPA_Q4_REASONING_LABELS";
// FROZEN 2026-05-19: see futurebuild/05 §16.
// TASK-PY-G-051 — Q4 non-trivial-on-Pass annotation rows.
pub const CF_MEJEPA_Q4_PASS_ANNOTATIONS: &str = "CF_MEJEPA_Q4_PASS_ANNOTATIONS";
// FROZEN 2026-05-19: Q4 entries are frozen/display-only. The CF remains open
// for non-Q4 calibration rows until the next schema-version cleanup.
// TASK-PY-G-050 / TASK-PY-G-012 — per-head calibration rows.
pub const CF_MEJEPA_HEAD_CALIBRATIONS: &str = "CF_MEJEPA_HEAD_CALIBRATIONS";
// TASK-PY-G-113 — sidecar provenance for every ship-gate-eligible threshold.
pub const CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE: &str =
    "CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE";
pub const FROZEN_Q4_CFS: &[&str] = &[
    CF_MEJEPA_Q4_SECURITY_LABELS,
    CF_MEJEPA_Q4_PERF_LABELS,
    CF_MEJEPA_Q4_ACCURACY_LABELS,
    CF_MEJEPA_Q4_COST_LABELS,
    CF_MEJEPA_Q4_REASONING_LABELS,
    CF_MEJEPA_Q4_PASS_ANNOTATIONS,
];
pub const FROZEN_Q4_CALIBRATION_KEY_PREFIX: &str = "q4cal::";
pub const FROZEN_Q4_CALIBRATION_COUNT_KEY: &str = "CF_MEJEPA_HEAD_CALIBRATIONS:q4cal::*";
// TASK-PY-G-044 — per-cell multi-head contradiction abstain thresholds.
pub const CF_MEJEPA_CONTRADICTION_THRESHOLDS: &str = "CF_MEJEPA_CONTRADICTION_THRESHOLDS";
// TASK-PY-G-090 — discovered slot-pair consensus/contradiction relationship patterns.
pub const CF_MEJEPA_CONSTELLATION_PATTERNS: &str = "CF_MEJEPA_CONSTELLATION_PATTERNS";
// TASK-IP-003 — per-cell connectome topology features over the slot-preserving
// cross-embedder correlation tensor.
pub const CF_MEJEPA_CONNECTOME_TOPOLOGY_FEATURES: &str = "CF_MEJEPA_CONNECTOME_TOPOLOGY_FEATURES";
// TASK-PY-G-110 — deterministic meaning labels over frozen embedder regions,
// cross-embedder relationships, and composed failure-mode predictions.
pub const CF_MEJEPA_FAILURE_MODE_LEVEL0: &str = "CF_MEJEPA_FAILURE_MODE_LEVEL0";
pub const CF_MEJEPA_FAILURE_MODE_VOCABULARY: &str = "CF_MEJEPA_FAILURE_MODE_VOCABULARY";
pub const CF_MEJEPA_FAILURE_MODE_LEVEL1: &str = "CF_MEJEPA_FAILURE_MODE_LEVEL1";
pub const CF_MEJEPA_FAILURE_MODE_LEVEL2_SKILLS: &str = "CF_MEJEPA_FAILURE_MODE_LEVEL2_SKILLS";
pub const CF_MEJEPA_FAILURE_MODE_LEVEL3_CONSTELLATIONS: &str =
    "CF_MEJEPA_FAILURE_MODE_LEVEL3_CONSTELLATIONS";
pub const CF_MEJEPA_NAMED_PREDICTIONS: &str = "CF_MEJEPA_NAMED_PREDICTIONS";
// TASK-PY-G-118 — live chunks expose their many-to-many participation in
// ordered skills and higher-level consequence patterns.
pub const CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP: &str = "CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP";
pub const CF_MEJEPA_SKILL_REVERSE_INDEX: &str = "CF_MEJEPA_SKILL_REVERSE_INDEX";
pub const CF_MEJEPA_SKILL_LIFECYCLE_AUDIT: &str = "CF_MEJEPA_SKILL_LIFECYCLE_AUDIT";
// TASK-PY-G-117 / TASK-PY-G-112 — deterministic accepted-label substrate and
// mistake-loop state. Accepted labels stay separate from flat panel vectors so
// prediction/replay can cite slot, pair, group, evidence-set, and skill IDs.
pub const CF_MEJEPA_ACCEPTED_LABEL_REGISTRY: &str = "CF_MEJEPA_ACCEPTED_LABEL_REGISTRY";
pub const CF_MEJEPA_LABEL_USEFULNESS_METRICS: &str = "CF_MEJEPA_LABEL_USEFULNESS_METRICS";
pub const CF_MEJEPA_FAILURE_EVIDENCE_SETS: &str = "CF_MEJEPA_FAILURE_EVIDENCE_SETS";
pub const CF_MEJEPA_MISTAKE_LOG: &str = "CF_MEJEPA_MISTAKE_LOG";
pub const CF_MEJEPA_MISTAKE_REPLAY_PRIORITY: &str = "CF_MEJEPA_MISTAKE_REPLAY_PRIORITY";
pub const CF_MEJEPA_ONLINE_HEAD_STATE: &str = "CF_MEJEPA_ONLINE_HEAD_STATE";
// TASK-RWD-209 / TASK-PY-G-075 — composite reward-signal labels.
pub const CF_MEJEPA_COVERAGE_SIGNALS: &str = "CF_MEJEPA_COVERAGE_SIGNALS";
pub const CF_MEJEPA_COMPLEXITY_SIGNALS: &str = "CF_MEJEPA_COMPLEXITY_SIGNALS";
pub const CF_MEJEPA_CHURN_SIGNALS: &str = "CF_MEJEPA_CHURN_SIGNALS";
pub const CF_MEJEPA_DOC_COVERAGE_SIGNALS: &str = "CF_MEJEPA_DOC_COVERAGE_SIGNALS";
pub const CF_MEJEPA_DEP_CVE_SIGNALS: &str = "CF_MEJEPA_DEP_CVE_SIGNALS";
// TASK-RWD-205 — Python E_TypeGraph call-site type evidence.
pub const CF_MEJEPA_TYPE_GRAPH_SIGNALS: &str = "CF_MEJEPA_TYPE_GRAPH_SIGNALS";
// TASK-RWD-206 — runtime telemetry prediction labels and symbol profiles.
pub const CF_MEJEPA_TELEMETRY_SIGNALS: &str = "CF_MEJEPA_TELEMETRY_SIGNALS";
// TASK-RWD-207 — live-session state rows.
pub const CF_MEJEPA_LIVE_SESSION_SIGNALS: &str = "CF_MEJEPA_LIVE_SESSION_SIGNALS";
// TASK-PY-G-059 — source chunk secret-redaction audit rows.
pub const CF_MEJEPA_REDACTION_LOG: &str = "CF_MEJEPA_REDACTION_LOG";
// TASK-RWD-315 — fail-closed signal-drop events for reward-signal auditability.
pub const CF_MEJEPA_SIGNAL_DROP_LOG: &str = "CF_MEJEPA_SIGNAL_DROP_LOG";
// TASK-RWD-210 / TASK-PY-G-068 — prioritized M(t) replay buffer rows.
pub const CF_MEJEPA_REPLAY_BUFFER: &str = "CF_MEJEPA_REPLAY_BUFFER";
// TASK-PY-G-053 — oracle-derived online observe reward rows for train sampling.
pub const CF_MEJEPA_SAMPLER_REWARDS: &str = "CF_MEJEPA_SAMPLER_REWARDS";
// TASK-RWD-211 / TASK-PY-G-067 — accepted/refuted system-proposed
// constellation/fingerprint growth rows from the novel-pattern gate.
pub const CF_MEJEPA_ONTOLOGY_GROWTH_AUDIT: &str = "CF_MEJEPA_ONTOLOGY_GROWTH_AUDIT";
// TASK-EK-003 — structural-hole mincut reports over ME-JEPA panel graphs.
pub const CF_MEJEPA_MINCUT_REPORTS: &str = "CF_MEJEPA_MINCUT_REPORTS";
// TASK-PY-G-007 — durable pairwise-MI matrix rows for embedder-panel audits.
pub const CF_MEJEPA_PAIRWISE_MI: &str = "CF_MEJEPA_PAIRWISE_MI";
// TASK-PY-G-042 — active patch-similarity exemplar index metadata.
pub const CF_MEJEPA_PATCH_SIMILARITY_META: &str = "CF_MEJEPA_PATCH_SIMILARITY_META";
// TASK-EK-002 — candidate frozen-instrument proposals and decisions.
pub const CF_MEJEPA_INSTRUMENT_PROPOSALS: &str = "CF_MEJEPA_INSTRUMENT_PROPOSALS";
// TASK-EK-018B — ranked absence-shape queue for self-designed embedder proposals.
pub const CF_MEJEPA_EMBEDDER_PROPOSALS: &str = "CF_MEJEPA_EMBEDDER_PROPOSALS";
// TASK-EK-018C — falsified dynamic-embedder candidate architectures.
pub const CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS: &str = "CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS";
// TASK-EK-018A — runtime dynamic-embedder hot-swap registry and audit trail.
pub const CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY: &str = "CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY";
pub const CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE: &str = "CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE";
// TASK-EK-016 — chunk dependency graph and PageRank-derived foundationality.
pub const CF_MEJEPA_CHUNK_DEPENDENCY_GRAPH: &str = "CF_MEJEPA_CHUNK_DEPENDENCY_GRAPH";
pub const CF_MEJEPA_CHUNK_FOUNDATIONALITY: &str = "CF_MEJEPA_CHUNK_FOUNDATIONALITY";
// TASK-EK-017 — library registration plus per-library/cross-library
// foundationality and reference counts.
pub const CF_MEJEPA_LIBRARY_REGISTRY: &str = "CF_MEJEPA_LIBRARY_REGISTRY";
pub const CF_MEJEPA_LIBRARY_FOUNDATIONALITY: &str = "CF_MEJEPA_LIBRARY_FOUNDATIONALITY";
pub const CF_MEJEPA_CROSS_LIBRARY_REFERENCES: &str = "CF_MEJEPA_CROSS_LIBRARY_REFERENCES";
// TASK-EK-016-ext — embedder dependency graph and PageRank-derived
// foundationality for static/dynamic embedders.
pub const CF_MEJEPA_EMBEDDER_DEPENDENCY_GRAPH: &str = "CF_MEJEPA_EMBEDDER_DEPENDENCY_GRAPH";
pub const CF_MEJEPA_EMBEDDER_FOUNDATIONALITY: &str = "CF_MEJEPA_EMBEDDER_FOUNDATIONALITY";
// TASK-FP-001/002 — first-class failure-shape fingerprint catalog.
pub const CF_MEJEPA_FAILURE_FINGERPRINTS: &str = "CF_MEJEPA_FAILURE_FINGERPRINTS";
pub const CF_MEJEPA_FINGERPRINT_REFERENCES: &str = "CF_MEJEPA_FINGERPRINT_REFERENCES";
pub const CF_MEJEPA_FINGERPRINT_REVERSE_INDEX: &str = "CF_MEJEPA_FINGERPRINT_REVERSE_INDEX";
pub const CF_MEJEPA_FINGERPRINT_CALIBRATION: &str = "CF_MEJEPA_FINGERPRINT_CALIBRATION";
pub const CF_MEJEPA_FINGERPRINT_AUDIT: &str = "CF_MEJEPA_FINGERPRINT_AUDIT";
pub const CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS: &str = "CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS";
// TASK-FP-008 — per-fingerprint EWC Fisher diagonal + CBP dormancy snapshots for
// catalog stability under continual learning (issue #317).
pub const CF_MEJEPA_FINGERPRINT_FISHER: &str = "CF_MEJEPA_FINGERPRINT_FISHER";
pub const CF_MEJEPA_FINGERPRINT_DORMANCY: &str = "CF_MEJEPA_FINGERPRINT_DORMANCY";
// TASK-PY-G-060 / TASK-FP-009 — 30-case adversarial Python corpus rows that
// feed the first-class failure-shape fingerprint catalog.
pub const CF_MEJEPA_ADVERSARIAL_CORPUS: &str = "CF_MEJEPA_ADVERSARIAL_CORPUS";

/// REQ-FLYWHEEL-10 grouping. Daemon openers extend their CF descriptor list
/// with this slice so the three new CFs land on disk during the first daemon
/// startup, even if no other code path has touched them yet.
pub const FLYWHEEL_CFS: &[&str] = &[
    CF_MEJEPA_DDA_SIGNALS,
    CF_MEJEPA_FAILURE_EXEMPLARS,
    CF_MEJEPA_AGENT_FEEDBACK,
    CF_MEJEPA_FLYWHEEL_JOB_RUNS,
    CF_MEJEPA_PARK_LIST,
];

pub const FINGERPRINT_CFS: &[&str] = &[
    CF_MEJEPA_FAILURE_FINGERPRINTS,
    CF_MEJEPA_FINGERPRINT_REFERENCES,
    CF_MEJEPA_FINGERPRINT_REVERSE_INDEX,
    CF_MEJEPA_FINGERPRINT_CALIBRATION,
    CF_MEJEPA_FINGERPRINT_AUDIT,
    CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS,
    CF_MEJEPA_FINGERPRINT_FISHER,
    CF_MEJEPA_FINGERPRINT_DORMANCY,
];

pub const ADVERSARIAL_CFS: &[&str] = &[CF_MEJEPA_ADVERSARIAL_CORPUS];

pub const CROSS_PANEL_CFS: &[&str] = &[
    CF_MEJEPA_PANEL_B_OBSERVATIONS,
    CF_MEJEPA_CROSS_PANEL_AGREEMENT,
];

pub const PATHWAY_CFS: &[&str] = &[
    CF_MEJEPA_PATHWAY_TREES,
    CF_MEJEPA_SURFACED_PATHWAYS,
    CF_MEJEPA_OPERATOR_PATHWAY_CHOICES,
];

pub const DOCKER_OUTCOME_CFS: &[&str] = &[CF_MEJEPA_DOCKER_OUTCOME_LABELS];

pub const OOD_HARVEST_CFS: &[&str] = &[CF_MEJEPA_OOD_HARVEST, CF_MEJEPA_OOD_CALIBRATIONS];

pub const THRESHOLD_CALIBRATION_CFS: &[&str] = &[CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE];

pub const FAILURE_MODE_CFS: &[&str] = &[
    CF_MEJEPA_FAILURE_MODE_LEVEL0,
    CF_MEJEPA_FAILURE_MODE_VOCABULARY,
    CF_MEJEPA_FAILURE_MODE_LEVEL1,
    CF_MEJEPA_FAILURE_MODE_LEVEL2_SKILLS,
    CF_MEJEPA_FAILURE_MODE_LEVEL3_CONSTELLATIONS,
    CF_MEJEPA_NAMED_PREDICTIONS,
    CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP,
    CF_MEJEPA_SKILL_REVERSE_INDEX,
    CF_MEJEPA_SKILL_LIFECYCLE_AUDIT,
    CF_MEJEPA_ACCEPTED_LABEL_REGISTRY,
    CF_MEJEPA_LABEL_USEFULNESS_METRICS,
    CF_MEJEPA_FAILURE_EVIDENCE_SETS,
];

pub const REWARD_SIGNAL_CFS: &[&str] = &[
    CF_MEJEPA_COVERAGE_SIGNALS,
    CF_MEJEPA_COMPLEXITY_SIGNALS,
    CF_MEJEPA_CHURN_SIGNALS,
    CF_MEJEPA_DOC_COVERAGE_SIGNALS,
    CF_MEJEPA_DEP_CVE_SIGNALS,
    CF_MEJEPA_TYPE_GRAPH_SIGNALS,
    CF_MEJEPA_TELEMETRY_SIGNALS,
    CF_MEJEPA_LIVE_SESSION_SIGNALS,
    CF_MEJEPA_REDACTION_LOG,
    CF_MEJEPA_CLAIM_RECONCILIATION,
    CF_MEJEPA_SIGNAL_DROP_LOG,
    CF_MEJEPA_REPLAY_BUFFER,
    CF_MEJEPA_MISTAKE_LOG,
    CF_MEJEPA_MISTAKE_REPLAY_PRIORITY,
    CF_MEJEPA_ONLINE_HEAD_STATE,
    CF_MEJEPA_SAMPLER_REWARDS,
    CF_MEJEPA_ONTOLOGY_GROWTH_AUDIT,
    CF_MEJEPA_CONSTELLATION_REFRESH_LOG,
];

pub const EXPLANATORY_KNOWLEDGE_CFS: &[&str] = &[
    CF_MEJEPA_MINCUT_REPORTS,
    CF_MEJEPA_PAIRWISE_MI,
    CF_MEJEPA_PATCH_SIMILARITY_META,
    CF_MEJEPA_INSTRUMENT_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS,
    CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY,
    CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE,
    CF_MEJEPA_CHUNK_DEPENDENCY_GRAPH,
    CF_MEJEPA_CHUNK_FOUNDATIONALITY,
    CF_MEJEPA_LIBRARY_REGISTRY,
    CF_MEJEPA_LIBRARY_FOUNDATIONALITY,
    CF_MEJEPA_CROSS_LIBRARY_REFERENCES,
    CF_MEJEPA_EMBEDDER_DEPENDENCY_GRAPH,
    CF_MEJEPA_EMBEDDER_FOUNDATIONALITY,
    CF_MEJEPA_OPERATOR_CONTRIBUTIONS,
    CF_MEJEPA_CURIOSITY_TELEMETRY,
];

pub const SELF_HEALING_CFS: &[&str] = &[
    CF_MEJEPA_FISHER_SNAPSHOTS,
    CF_MEJEPA_DRIFT_WINDOW,
    CF_MEJEPA_DRIFT_HISTORY,
    CF_MEJEPA_HEAL_REPORTS,
    CF_MEJEPA_DISTILL_STEPS,
    CF_MEJEPA_ACTIVE_POINTERS,
    CF_MEJEPA_CALIBRATION_HISTORY,
];

pub const SELF_HEALING_REFERENCED_CFS: &[&str] = &[
    CF_MEJEPA_FISHER_SNAPSHOTS,
    CF_MEJEPA_DRIFT_WINDOW,
    CF_MEJEPA_DRIFT_HISTORY,
    CF_MEJEPA_HEAL_REPORTS,
    CF_MEJEPA_DISTILL_STEPS,
    CF_MEJEPA_ACTIVE_POINTERS,
    CF_MEJEPA_CALIBRATION_HISTORY,
    CF_MEJEPA_PLASTICITY_HISTORY,
    CF_MEJEPA_WEIGHT_BLOBS,
    CF_MEJEPA_SHIFT_WATERMARK,
    CF_MEJEPA_TRAIN_CERTS,
];

pub const INFER_CFS: &[&str] = &[
    CF_MEJEPA_CALIBRATION_HISTORY,
    CF_MEJEPA_LIVE_PREDICTIONS,
    CF_MEJEPA_LIVE_SESSION_TRACES,
    CF_MEJEPA_HIERARCHICAL_PREDICTIONS,
    CF_MEJEPA_ORACLE_VERDICTS,
    CF_MEJEPA_PREDICTION_VERIFICATIONS,
    CF_MEJEPA_REALITY_IMPACT,
    CF_MEJEPA_Q5_CALIBRATIONS,
    CF_MEJEPA_CLAIM_RECONCILIATION,
    CF_MEJEPA_PROJECT_REPORTS,
    CF_MEJEPA_STRESS_RUNS,
    CF_MEJEPA_SYNTHETIC_STRESS_RESULTS,
    CF_MEJEPA_TRAIN_CERTS,
    CF_MEJEPA_PANELS,
    CF_MEJEPA_PANEL_GRAPHS,
    CF_MEJEPA_PANEL_B_OBSERVATIONS,
    CF_MEJEPA_CROSS_PANEL_AGREEMENT,
    CF_MEJEPA_PATHWAY_TREES,
    CF_MEJEPA_SURFACED_PATHWAYS,
    CF_MEJEPA_OPERATOR_PATHWAY_CHOICES,
    CF_MEJEPA_DOCKER_OUTCOME_LABELS,
    CF_MEJEPA_SHIFT_WATERMARK,
    CF_MEJEPA_PANEL_CACHE,
    CF_MEJEPA_PANEL_META,
    CF_MEJEPA_AUX_SIGNALS_OVERRIDES,
    CF_MEJEPA_EVAL_REPORTS,
    CF_MEJEPA_ABLATION_REPORTS,
    CF_MEJEPA_TASK_GRAPH,
    CF_MEJEPA_TASK_GRAPH_HISTORY,
    CF_MEJEPA_ACTIVE_LEARNING_QUEUE,
    CF_MEJEPA_FAILURE_FINGERPRINTS,
    CF_MEJEPA_FINGERPRINT_REFERENCES,
    CF_MEJEPA_FINGERPRINT_REVERSE_INDEX,
    CF_MEJEPA_FINGERPRINT_CALIBRATION,
    CF_MEJEPA_FINGERPRINT_AUDIT,
    CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS,
    CF_MEJEPA_FINGERPRINT_FISHER,
    CF_MEJEPA_FINGERPRINT_DORMANCY,
    CF_MEJEPA_ADVERSARIAL_CORPUS,
    CF_MEJEPA_ACTIVE_LEARNING_LABELS,
    CF_MEJEPA_ACTIVE_LEARNING_EVICTIONS,
    CF_MEJEPA_OOD_ESCALATIONS,
    CF_MEJEPA_OOD_HARVEST,
    CF_MEJEPA_OOD_CALIBRATIONS,
    CF_MEJEPA_CURIOSITY_TELEMETRY,
    CF_MEJEPA_RESEARCH_QUESTIONS,
    CF_MEJEPA_MODEL_PROMOTIONS,
    CF_MEJEPA_PRODUCTION_TELEMETRY,
    CF_MEJEPA_DDA_SIGNALS,
    CF_MEJEPA_HEAD_PROJECTION_REGISTRY,
    CF_MEJEPA_FAILURE_EXEMPLARS,
    CF_MEJEPA_AGENT_FEEDBACK,
    CF_MEJEPA_FLYWHEEL_JOB_RUNS,
    CF_MEJEPA_OPERATOR_OVERRIDES,
    CF_MEJEPA_OPERATOR_CONTRIBUTIONS,
    CF_MEJEPA_LABEL_TRANSFER_DECISIONS,
    CF_MEJEPA_PARK_LIST,
    CF_MEJEPA_COLD_CELL_METRICS,
    CF_MEJEPA_STATIC_ANALYSIS_SIGNALS,
    CF_MEJEPA_Q4_SECURITY_LABELS,
    CF_MEJEPA_Q4_PERF_LABELS,
    CF_MEJEPA_Q4_ACCURACY_LABELS,
    CF_MEJEPA_Q4_COST_LABELS,
    CF_MEJEPA_Q4_REASONING_LABELS,
    CF_MEJEPA_Q4_PASS_ANNOTATIONS,
    CF_MEJEPA_HEAD_CALIBRATIONS,
    CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE,
    CF_MEJEPA_CONTRADICTION_THRESHOLDS,
    CF_MEJEPA_CONSTELLATION_PATTERNS,
    CF_MEJEPA_CONNECTOME_TOPOLOGY_FEATURES,
    CF_MEJEPA_FAILURE_MODE_LEVEL0,
    CF_MEJEPA_FAILURE_MODE_VOCABULARY,
    CF_MEJEPA_FAILURE_MODE_LEVEL1,
    CF_MEJEPA_FAILURE_MODE_LEVEL2_SKILLS,
    CF_MEJEPA_FAILURE_MODE_LEVEL3_CONSTELLATIONS,
    CF_MEJEPA_NAMED_PREDICTIONS,
    CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP,
    CF_MEJEPA_SKILL_REVERSE_INDEX,
    CF_MEJEPA_SKILL_LIFECYCLE_AUDIT,
    CF_MEJEPA_ACCEPTED_LABEL_REGISTRY,
    CF_MEJEPA_LABEL_USEFULNESS_METRICS,
    CF_MEJEPA_FAILURE_EVIDENCE_SETS,
    CF_MEJEPA_MISTAKE_LOG,
    CF_MEJEPA_MISTAKE_REPLAY_PRIORITY,
    CF_MEJEPA_ONLINE_HEAD_STATE,
    CF_MEJEPA_COVERAGE_SIGNALS,
    CF_MEJEPA_COMPLEXITY_SIGNALS,
    CF_MEJEPA_CHURN_SIGNALS,
    CF_MEJEPA_DOC_COVERAGE_SIGNALS,
    CF_MEJEPA_DEP_CVE_SIGNALS,
    CF_MEJEPA_TYPE_GRAPH_SIGNALS,
    CF_MEJEPA_TELEMETRY_SIGNALS,
    CF_MEJEPA_LIVE_SESSION_SIGNALS,
    CF_MEJEPA_REDACTION_LOG,
    CF_MEJEPA_SIGNAL_DROP_LOG,
    CF_MEJEPA_REPLAY_BUFFER,
    CF_MEJEPA_SAMPLER_REWARDS,
    CF_MEJEPA_ONTOLOGY_GROWTH_AUDIT,
    CF_MEJEPA_MINCUT_REPORTS,
    CF_MEJEPA_PAIRWISE_MI,
    CF_MEJEPA_PATCH_SIMILARITY_META,
    CF_MEJEPA_INSTRUMENT_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS,
    CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY,
    CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE,
    CF_MEJEPA_CHUNK_DEPENDENCY_GRAPH,
    CF_MEJEPA_CHUNK_FOUNDATIONALITY,
    CF_MEJEPA_LIBRARY_REGISTRY,
    CF_MEJEPA_LIBRARY_FOUNDATIONALITY,
    CF_MEJEPA_CROSS_LIBRARY_REFERENCES,
    CF_MEJEPA_EMBEDDER_DEPENDENCY_GRAPH,
    CF_MEJEPA_EMBEDDER_FOUNDATIONALITY,
    CF_MEJEPA_CONSTELLATION_REFRESH_LOG,
];

pub const EVAL_CFS: &[&str] = &[
    CF_MEJEPA_EVAL_REPORTS,
    CF_MEJEPA_ABLATION_REPORTS,
    CF_MEJEPA_TASK_GRAPH,
    CF_MEJEPA_TASK_GRAPH_HISTORY,
    CF_MEJEPA_ACTIVE_LEARNING_QUEUE,
    CF_MEJEPA_FAILURE_FINGERPRINTS,
    CF_MEJEPA_FINGERPRINT_REFERENCES,
    CF_MEJEPA_FINGERPRINT_REVERSE_INDEX,
    CF_MEJEPA_FINGERPRINT_CALIBRATION,
    CF_MEJEPA_FINGERPRINT_AUDIT,
    CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS,
    CF_MEJEPA_ADVERSARIAL_CORPUS,
    CF_MEJEPA_SYNTHETIC_STRESS_RESULTS,
    CF_MEJEPA_ACTIVE_LEARNING_LABELS,
    CF_MEJEPA_ACTIVE_LEARNING_EVICTIONS,
    CF_MEJEPA_OOD_ESCALATIONS,
    CF_MEJEPA_OOD_HARVEST,
    CF_MEJEPA_OOD_CALIBRATIONS,
    CF_MEJEPA_CURIOSITY_TELEMETRY,
    CF_MEJEPA_RESEARCH_QUESTIONS,
    CF_MEJEPA_MODEL_PROMOTIONS,
    CF_MEJEPA_PRODUCTION_TELEMETRY,
    CF_MEJEPA_FLYWHEEL_JOB_RUNS,
    CF_MEJEPA_LABEL_TRANSFER_DECISIONS,
    CF_MEJEPA_PARK_LIST,
    CF_MEJEPA_COLD_CELL_METRICS,
    CF_MEJEPA_STATIC_ANALYSIS_SIGNALS,
    CF_MEJEPA_Q4_SECURITY_LABELS,
    CF_MEJEPA_Q4_PERF_LABELS,
    CF_MEJEPA_Q4_ACCURACY_LABELS,
    CF_MEJEPA_Q4_COST_LABELS,
    CF_MEJEPA_Q4_REASONING_LABELS,
    CF_MEJEPA_Q4_PASS_ANNOTATIONS,
    CF_MEJEPA_HEAD_CALIBRATIONS,
    CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE,
    CF_MEJEPA_CONTRADICTION_THRESHOLDS,
    CF_MEJEPA_CONSTELLATION_PATTERNS,
    CF_MEJEPA_CONNECTOME_TOPOLOGY_FEATURES,
    CF_MEJEPA_FAILURE_MODE_LEVEL0,
    CF_MEJEPA_FAILURE_MODE_VOCABULARY,
    CF_MEJEPA_FAILURE_MODE_LEVEL1,
    CF_MEJEPA_FAILURE_MODE_LEVEL2_SKILLS,
    CF_MEJEPA_FAILURE_MODE_LEVEL3_CONSTELLATIONS,
    CF_MEJEPA_NAMED_PREDICTIONS,
    CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP,
    CF_MEJEPA_SKILL_REVERSE_INDEX,
    CF_MEJEPA_SKILL_LIFECYCLE_AUDIT,
    CF_MEJEPA_ACCEPTED_LABEL_REGISTRY,
    CF_MEJEPA_LABEL_USEFULNESS_METRICS,
    CF_MEJEPA_FAILURE_EVIDENCE_SETS,
    CF_MEJEPA_MISTAKE_LOG,
    CF_MEJEPA_MISTAKE_REPLAY_PRIORITY,
    CF_MEJEPA_ONLINE_HEAD_STATE,
    CF_MEJEPA_COVERAGE_SIGNALS,
    CF_MEJEPA_COMPLEXITY_SIGNALS,
    CF_MEJEPA_CHURN_SIGNALS,
    CF_MEJEPA_DOC_COVERAGE_SIGNALS,
    CF_MEJEPA_DEP_CVE_SIGNALS,
    CF_MEJEPA_TYPE_GRAPH_SIGNALS,
    CF_MEJEPA_TELEMETRY_SIGNALS,
    CF_MEJEPA_LIVE_SESSION_SIGNALS,
    CF_MEJEPA_REDACTION_LOG,
    CF_MEJEPA_SIGNAL_DROP_LOG,
    CF_MEJEPA_REPLAY_BUFFER,
    CF_MEJEPA_SAMPLER_REWARDS,
    CF_MEJEPA_ONTOLOGY_GROWTH_AUDIT,
    CF_MEJEPA_MINCUT_REPORTS,
    CF_MEJEPA_PAIRWISE_MI,
    CF_MEJEPA_PATCH_SIMILARITY_META,
    CF_MEJEPA_INSTRUMENT_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS,
    CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY,
    CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE,
    CF_MEJEPA_CHUNK_DEPENDENCY_GRAPH,
    CF_MEJEPA_CHUNK_FOUNDATIONALITY,
    CF_MEJEPA_LIBRARY_REGISTRY,
    CF_MEJEPA_LIBRARY_FOUNDATIONALITY,
    CF_MEJEPA_CROSS_LIBRARY_REFERENCES,
    CF_MEJEPA_OPERATOR_CONTRIBUTIONS,
];

pub const HYGIENE_CFS: &[&str] = &[
    CF_MEJEPA_MUTATION_CORPUS,
    CF_MEJEPA_LIVE_ATTEMPT_CORPUS,
    CF_MEJEPA_PANEL_META,
    CF_MEJEPA_QUOTA_STATE,
    CF_MEJEPA_WEIGHT_BLOBS,
    CF_MEJEPA_WEIGHT_BLOBS_META,
    CF_MEJEPA_WITNESS_CHAIN,
    CF_MEJEPA_WITNESS_SEGMENT_META,
    CF_MEJEPA_PANEL_CACHE,
    CF_MEJEPA_PANEL_DISK_OVERFLOW,
    CF_MEJEPA_CALIBRATION_HISTORY,
    CF_MEJEPA_AUX_SIGNALS_OVERRIDES,
    CF_MEJEPA_SHIFT_WATERMARK,
    CF_MEJEPA_TRAIN_CERTS,
    CF_MEJEPA_GC_HISTORY,
    CF_MEJEPA_EVAL_REPORTS,
    CF_MEJEPA_ABLATION_REPORTS,
    CF_MEJEPA_TASK_GRAPH,
    CF_MEJEPA_TASK_GRAPH_HISTORY,
    CF_MEJEPA_ACTIVE_LEARNING_QUEUE,
    CF_MEJEPA_HIERARCHICAL_PREDICTIONS,
    CF_MEJEPA_PREDICTION_VERIFICATIONS,
    CF_MEJEPA_REALITY_IMPACT,
    CF_MEJEPA_Q5_CALIBRATIONS,
    CF_MEJEPA_CLAIM_RECONCILIATION,
    CF_MEJEPA_PROJECT_REPORTS,
    CF_MEJEPA_STRESS_RUNS,
    CF_MEJEPA_SYNTHETIC_STRESS_RESULTS,
    CF_MEJEPA_PANEL_B_OBSERVATIONS,
    CF_MEJEPA_CROSS_PANEL_AGREEMENT,
    CF_MEJEPA_PATHWAY_TREES,
    CF_MEJEPA_SURFACED_PATHWAYS,
    CF_MEJEPA_OPERATOR_PATHWAY_CHOICES,
    CF_MEJEPA_DOCKER_OUTCOME_LABELS,
    CF_MEJEPA_LIVE_SESSION_TRACES,
    CF_MEJEPA_FAILURE_FINGERPRINTS,
    CF_MEJEPA_FINGERPRINT_REFERENCES,
    CF_MEJEPA_FINGERPRINT_REVERSE_INDEX,
    CF_MEJEPA_FINGERPRINT_CALIBRATION,
    CF_MEJEPA_FINGERPRINT_AUDIT,
    CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS,
    CF_MEJEPA_FINGERPRINT_FISHER,
    CF_MEJEPA_FINGERPRINT_DORMANCY,
    CF_MEJEPA_ADVERSARIAL_CORPUS,
    CF_MEJEPA_ACTIVE_LEARNING_LABELS,
    CF_MEJEPA_ACTIVE_LEARNING_EVICTIONS,
    CF_MEJEPA_OOD_ESCALATIONS,
    CF_MEJEPA_OOD_HARVEST,
    CF_MEJEPA_OOD_CALIBRATIONS,
    CF_MEJEPA_CURIOSITY_TELEMETRY,
    CF_MEJEPA_RESEARCH_QUESTIONS,
    CF_MEJEPA_MODEL_PROMOTIONS,
    CF_MEJEPA_PRODUCTION_TELEMETRY,
    CF_MEJEPA_OPERATOR_CONTRIBUTIONS,
    CF_MEJEPA_LABEL_TRANSFER_DECISIONS,
    CF_MEJEPA_COLD_CELL_METRICS,
    CF_MEJEPA_STATIC_ANALYSIS_SIGNALS,
    CF_MEJEPA_Q4_SECURITY_LABELS,
    CF_MEJEPA_Q4_PERF_LABELS,
    CF_MEJEPA_Q4_ACCURACY_LABELS,
    CF_MEJEPA_Q4_COST_LABELS,
    CF_MEJEPA_Q4_REASONING_LABELS,
    CF_MEJEPA_Q4_PASS_ANNOTATIONS,
    CF_MEJEPA_HEAD_CALIBRATIONS,
    CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE,
    CF_MEJEPA_CONTRADICTION_THRESHOLDS,
    CF_MEJEPA_CONSTELLATION_PATTERNS,
    CF_MEJEPA_CONNECTOME_TOPOLOGY_FEATURES,
    CF_MEJEPA_FAILURE_MODE_LEVEL0,
    CF_MEJEPA_FAILURE_MODE_VOCABULARY,
    CF_MEJEPA_FAILURE_MODE_LEVEL1,
    CF_MEJEPA_FAILURE_MODE_LEVEL2_SKILLS,
    CF_MEJEPA_FAILURE_MODE_LEVEL3_CONSTELLATIONS,
    CF_MEJEPA_NAMED_PREDICTIONS,
    CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP,
    CF_MEJEPA_SKILL_REVERSE_INDEX,
    CF_MEJEPA_SKILL_LIFECYCLE_AUDIT,
    CF_MEJEPA_ACCEPTED_LABEL_REGISTRY,
    CF_MEJEPA_LABEL_USEFULNESS_METRICS,
    CF_MEJEPA_FAILURE_EVIDENCE_SETS,
    CF_MEJEPA_MISTAKE_LOG,
    CF_MEJEPA_MISTAKE_REPLAY_PRIORITY,
    CF_MEJEPA_ONLINE_HEAD_STATE,
    CF_MEJEPA_COVERAGE_SIGNALS,
    CF_MEJEPA_COMPLEXITY_SIGNALS,
    CF_MEJEPA_CHURN_SIGNALS,
    CF_MEJEPA_DOC_COVERAGE_SIGNALS,
    CF_MEJEPA_DEP_CVE_SIGNALS,
    CF_MEJEPA_TYPE_GRAPH_SIGNALS,
    CF_MEJEPA_TELEMETRY_SIGNALS,
    CF_MEJEPA_LIVE_SESSION_SIGNALS,
    CF_MEJEPA_REDACTION_LOG,
    CF_MEJEPA_SIGNAL_DROP_LOG,
    CF_MEJEPA_REPLAY_BUFFER,
    CF_MEJEPA_SAMPLER_REWARDS,
    CF_MEJEPA_MINCUT_REPORTS,
    CF_MEJEPA_PAIRWISE_MI,
    CF_MEJEPA_PATCH_SIMILARITY_META,
    CF_MEJEPA_INSTRUMENT_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS,
    CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY,
    CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE,
    CF_MEJEPA_CHUNK_DEPENDENCY_GRAPH,
    CF_MEJEPA_CHUNK_FOUNDATIONALITY,
    CF_MEJEPA_LIBRARY_REGISTRY,
    CF_MEJEPA_LIBRARY_FOUNDATIONALITY,
    CF_MEJEPA_CROSS_LIBRARY_REFERENCES,
    CF_MEJEPA_EMBEDDER_DEPENDENCY_GRAPH,
    CF_MEJEPA_EMBEDDER_FOUNDATIONALITY,
    CF_MEJEPA_CONSTELLATION_REFRESH_LOG,
];

pub const TCT_CFS: &[&str] = &[
    CF_MEJEPA_CONSTELLATION,
    CF_MEJEPA_GUARD_DECISIONS,
    CF_MEJEPA_CONSTELLATION_REFRESH_REPORTS,
    CF_MEJEPA_CONSTELLATION_REFRESH_LOG,
];

/// Canonical, duplicate-free list opened by ME-JEPA hygiene/runtime databases.
///
/// This is intentionally explicit instead of synthesized at runtime: downstream
/// storage code uses the length as part of the full RocksDB schema contract, so
/// adding or removing a CF must be a visible schema change.
pub const ALL_HYGIENE_REFERENCED_CFS: &[&str] = &[
    CF_MEJEPA_FISHER_SNAPSHOTS,
    CF_MEJEPA_DRIFT_WINDOW,
    CF_MEJEPA_DRIFT_HISTORY,
    CF_MEJEPA_HEAL_REPORTS,
    CF_MEJEPA_DISTILL_STEPS,
    CF_MEJEPA_ACTIVE_POINTERS,
    CF_MEJEPA_CALIBRATION_HISTORY,
    CF_MEJEPA_PLASTICITY_HISTORY,
    CF_MEJEPA_WEIGHT_BLOBS,
    CF_MEJEPA_SHIFT_WATERMARK,
    CF_MEJEPA_TRAIN_CERTS,
    CF_MEJEPA_LIVE_PREDICTIONS,
    CF_MEJEPA_LIVE_SESSION_TRACES,
    CF_MEJEPA_HIERARCHICAL_PREDICTIONS,
    CF_MEJEPA_ORACLE_VERDICTS,
    CF_MEJEPA_PREDICTION_VERIFICATIONS,
    CF_MEJEPA_REALITY_IMPACT,
    CF_MEJEPA_Q5_CALIBRATIONS,
    CF_MEJEPA_CLAIM_RECONCILIATION,
    CF_MEJEPA_PROJECT_REPORTS,
    CF_MEJEPA_STRESS_RUNS,
    CF_MEJEPA_SYNTHETIC_STRESS_RESULTS,
    CF_MEJEPA_PANELS,
    CF_MEJEPA_PANEL_GRAPHS,
    CF_MEJEPA_PANEL_B_OBSERVATIONS,
    CF_MEJEPA_CROSS_PANEL_AGREEMENT,
    CF_MEJEPA_PATHWAY_TREES,
    CF_MEJEPA_SURFACED_PATHWAYS,
    CF_MEJEPA_OPERATOR_PATHWAY_CHOICES,
    CF_MEJEPA_DOCKER_OUTCOME_LABELS,
    CF_MEJEPA_PANEL_CACHE,
    CF_MEJEPA_PANEL_META,
    CF_MEJEPA_AUX_SIGNALS_OVERRIDES,
    CF_MEJEPA_EVAL_REPORTS,
    CF_MEJEPA_ABLATION_REPORTS,
    CF_MEJEPA_TASK_GRAPH,
    CF_MEJEPA_TASK_GRAPH_HISTORY,
    CF_MEJEPA_ACTIVE_LEARNING_QUEUE,
    CF_MEJEPA_FAILURE_FINGERPRINTS,
    CF_MEJEPA_FINGERPRINT_REFERENCES,
    CF_MEJEPA_FINGERPRINT_REVERSE_INDEX,
    CF_MEJEPA_FINGERPRINT_CALIBRATION,
    CF_MEJEPA_FINGERPRINT_AUDIT,
    CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS,
    CF_MEJEPA_FINGERPRINT_FISHER,
    CF_MEJEPA_FINGERPRINT_DORMANCY,
    CF_MEJEPA_ADVERSARIAL_CORPUS,
    CF_MEJEPA_ACTIVE_LEARNING_LABELS,
    CF_MEJEPA_ACTIVE_LEARNING_EVICTIONS,
    CF_MEJEPA_OOD_ESCALATIONS,
    CF_MEJEPA_OOD_HARVEST,
    CF_MEJEPA_OOD_CALIBRATIONS,
    CF_MEJEPA_CURIOSITY_TELEMETRY,
    CF_MEJEPA_RESEARCH_QUESTIONS,
    CF_MEJEPA_MODEL_PROMOTIONS,
    CF_MEJEPA_PRODUCTION_TELEMETRY,
    CF_MEJEPA_DDA_SIGNALS,
    CF_MEJEPA_HEAD_PROJECTION_REGISTRY,
    CF_MEJEPA_FAILURE_EXEMPLARS,
    CF_MEJEPA_AGENT_FEEDBACK,
    CF_MEJEPA_FLYWHEEL_JOB_RUNS,
    CF_MEJEPA_OPERATOR_OVERRIDES,
    CF_MEJEPA_OPERATOR_CONTRIBUTIONS,
    CF_MEJEPA_LABEL_TRANSFER_DECISIONS,
    CF_MEJEPA_PARK_LIST,
    CF_MEJEPA_COLD_CELL_METRICS,
    CF_MEJEPA_STATIC_ANALYSIS_SIGNALS,
    CF_MEJEPA_Q4_SECURITY_LABELS,
    CF_MEJEPA_Q4_PERF_LABELS,
    CF_MEJEPA_Q4_ACCURACY_LABELS,
    CF_MEJEPA_Q4_COST_LABELS,
    CF_MEJEPA_Q4_REASONING_LABELS,
    CF_MEJEPA_Q4_PASS_ANNOTATIONS,
    CF_MEJEPA_HEAD_CALIBRATIONS,
    CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE,
    CF_MEJEPA_CONTRADICTION_THRESHOLDS,
    CF_MEJEPA_CONSTELLATION_PATTERNS,
    CF_MEJEPA_CONNECTOME_TOPOLOGY_FEATURES,
    CF_MEJEPA_FAILURE_MODE_LEVEL0,
    CF_MEJEPA_FAILURE_MODE_VOCABULARY,
    CF_MEJEPA_FAILURE_MODE_LEVEL1,
    CF_MEJEPA_FAILURE_MODE_LEVEL2_SKILLS,
    CF_MEJEPA_FAILURE_MODE_LEVEL3_CONSTELLATIONS,
    CF_MEJEPA_NAMED_PREDICTIONS,
    CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP,
    CF_MEJEPA_SKILL_REVERSE_INDEX,
    CF_MEJEPA_SKILL_LIFECYCLE_AUDIT,
    CF_MEJEPA_ACCEPTED_LABEL_REGISTRY,
    CF_MEJEPA_LABEL_USEFULNESS_METRICS,
    CF_MEJEPA_FAILURE_EVIDENCE_SETS,
    CF_MEJEPA_MISTAKE_LOG,
    CF_MEJEPA_MISTAKE_REPLAY_PRIORITY,
    CF_MEJEPA_ONLINE_HEAD_STATE,
    CF_MEJEPA_COVERAGE_SIGNALS,
    CF_MEJEPA_COMPLEXITY_SIGNALS,
    CF_MEJEPA_CHURN_SIGNALS,
    CF_MEJEPA_DOC_COVERAGE_SIGNALS,
    CF_MEJEPA_DEP_CVE_SIGNALS,
    CF_MEJEPA_TYPE_GRAPH_SIGNALS,
    CF_MEJEPA_TELEMETRY_SIGNALS,
    CF_MEJEPA_LIVE_SESSION_SIGNALS,
    CF_MEJEPA_REDACTION_LOG,
    CF_MEJEPA_SIGNAL_DROP_LOG,
    CF_MEJEPA_REPLAY_BUFFER,
    CF_MEJEPA_SAMPLER_REWARDS,
    CF_MEJEPA_ONTOLOGY_GROWTH_AUDIT,
    CF_MEJEPA_MINCUT_REPORTS,
    CF_MEJEPA_PAIRWISE_MI,
    CF_MEJEPA_PATCH_SIMILARITY_META,
    CF_MEJEPA_INSTRUMENT_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSALS,
    CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS,
    CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY,
    CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE,
    CF_MEJEPA_CHUNK_DEPENDENCY_GRAPH,
    CF_MEJEPA_CHUNK_FOUNDATIONALITY,
    CF_MEJEPA_LIBRARY_REGISTRY,
    CF_MEJEPA_LIBRARY_FOUNDATIONALITY,
    CF_MEJEPA_CROSS_LIBRARY_REFERENCES,
    CF_MEJEPA_EMBEDDER_DEPENDENCY_GRAPH,
    CF_MEJEPA_EMBEDDER_FOUNDATIONALITY,
    CF_MEJEPA_CONSTELLATION_REFRESH_LOG,
    CF_MEJEPA_MUTATION_CORPUS,
    CF_MEJEPA_LIVE_ATTEMPT_CORPUS,
    CF_MEJEPA_QUOTA_STATE,
    CF_MEJEPA_WEIGHT_BLOBS_META,
    CF_MEJEPA_WITNESS_CHAIN,
    CF_MEJEPA_WITNESS_SEGMENT_META,
    CF_MEJEPA_PANEL_DISK_OVERFLOW,
    CF_MEJEPA_GC_HISTORY,
    CF_MEJEPA_CONSTELLATION,
    CF_MEJEPA_GUARD_DECISIONS,
    CF_MEJEPA_CONSTELLATION_REFRESH_REPORTS,
];

pub const MEJEPA_HYGIENE_REFERENCED_CF_COUNT: usize = ALL_HYGIENE_REFERENCED_CFS.len();

pub fn all_hygiene_referenced_cfs() -> Vec<&'static str> {
    ALL_HYGIENE_REFERENCED_CFS.to_vec()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_duplicate_hygiene_cfs() {
        let names = all_hygiene_referenced_cfs();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(names.len(), sorted.len());
        assert_eq!(names.len(), MEJEPA_HYGIENE_REFERENCED_CF_COUNT);
    }

    #[test]
    fn canonical_hygiene_cfs_match_group_union() {
        let mut generated = SELF_HEALING_REFERENCED_CFS.to_vec();
        for cf in INFER_CFS
            .iter()
            .chain(HYGIENE_CFS.iter())
            .chain(TCT_CFS.iter())
            .chain(FLYWHEEL_CFS.iter())
            .chain(FINGERPRINT_CFS.iter())
            .chain(ADVERSARIAL_CFS.iter())
            .chain(PATHWAY_CFS.iter())
            .chain(DOCKER_OUTCOME_CFS.iter())
            .chain(OOD_HARVEST_CFS.iter())
            .chain(THRESHOLD_CALIBRATION_CFS.iter())
            .chain(FAILURE_MODE_CFS.iter())
            .chain(REWARD_SIGNAL_CFS.iter())
            .chain(EXPLANATORY_KNOWLEDGE_CFS.iter())
        {
            if !generated.contains(cf) {
                generated.push(*cf);
            }
        }

        assert_eq!(
            ALL_HYGIENE_REFERENCED_CFS,
            generated.as_slice(),
            "canonical ME-JEPA CF list drifted from the grouped CF contract",
        );
    }

    #[test]
    fn flywheel_cfs_are_registered_in_daemon_opener() {
        let names = all_hygiene_referenced_cfs();
        for cf in FLYWHEEL_CFS {
            assert!(
                names.contains(cf),
                "FLYWHEEL CF {cf} missing from daemon opener; \
                 daemon startup would fail to create the column family on \
                 first run and downstream put_cf calls would panic.",
            );
        }
    }

    #[test]
    fn flywheel_cf_names_match_const_idents() {
        // REQ-FLYWHEEL-10 contract: the on-disk CF name MUST equal the
        // constant identifier, so renaming the constant forces a deliberate
        // (and grep-visible) data migration rather than a silent rename.
        assert_eq!(CF_MEJEPA_DDA_SIGNALS, "CF_MEJEPA_DDA_SIGNALS");
        assert_eq!(
            CF_MEJEPA_HEAD_PROJECTION_REGISTRY,
            "CF_MEJEPA_HEAD_PROJECTION_REGISTRY"
        );
        assert_eq!(CF_MEJEPA_FAILURE_EXEMPLARS, "CF_MEJEPA_FAILURE_EXEMPLARS");
        assert_eq!(CF_MEJEPA_AGENT_FEEDBACK, "CF_MEJEPA_AGENT_FEEDBACK");
        assert_eq!(CF_MEJEPA_FLYWHEEL_JOB_RUNS, "CF_MEJEPA_FLYWHEEL_JOB_RUNS");
        assert_eq!(
            CF_MEJEPA_PREDICTION_VERIFICATIONS,
            "CF_MEJEPA_PREDICTION_VERIFICATIONS"
        );
        assert_eq!(CF_MEJEPA_REALITY_IMPACT, "CF_MEJEPA_REALITY_IMPACT");
        assert_eq!(CF_MEJEPA_Q5_CALIBRATIONS, "CF_MEJEPA_Q5_CALIBRATIONS");
        assert_eq!(
            CF_MEJEPA_CLAIM_RECONCILIATION,
            "CF_MEJEPA_CLAIM_RECONCILIATION"
        );
        assert_eq!(CF_MEJEPA_PROJECT_REPORTS, "CF_MEJEPA_PROJECT_REPORTS");
        assert_eq!(CF_MEJEPA_STRESS_RUNS, "CF_MEJEPA_STRESS_RUNS");
        assert_eq!(
            CF_MEJEPA_SYNTHETIC_STRESS_RESULTS,
            "CF_MEJEPA_SYNTHETIC_STRESS_RESULTS"
        );
        assert_eq!(
            CF_MEJEPA_LIVE_SESSION_TRACES,
            "CF_MEJEPA_LIVE_SESSION_TRACES"
        );
        assert_eq!(
            CF_MEJEPA_HIERARCHICAL_PREDICTIONS,
            "CF_MEJEPA_HIERARCHICAL_PREDICTIONS"
        );
        assert_eq!(CF_MEJEPA_ABLATION_REPORTS, "CF_MEJEPA_ABLATION_REPORTS");
        assert_eq!(
            CF_MEJEPA_LABEL_TRANSFER_DECISIONS,
            "CF_MEJEPA_LABEL_TRANSFER_DECISIONS"
        );
        assert_eq!(CF_MEJEPA_COLD_CELL_METRICS, "CF_MEJEPA_COLD_CELL_METRICS");
        assert_eq!(
            CF_MEJEPA_STATIC_ANALYSIS_SIGNALS,
            "CF_MEJEPA_STATIC_ANALYSIS_SIGNALS"
        );
        assert_eq!(CF_MEJEPA_Q4_SECURITY_LABELS, "CF_MEJEPA_Q4_SECURITY_LABELS");
        assert_eq!(CF_MEJEPA_Q4_PERF_LABELS, "CF_MEJEPA_Q4_PERF_LABELS");
        assert_eq!(CF_MEJEPA_Q4_ACCURACY_LABELS, "CF_MEJEPA_Q4_ACCURACY_LABELS");
        assert_eq!(CF_MEJEPA_Q4_COST_LABELS, "CF_MEJEPA_Q4_COST_LABELS");
        assert_eq!(
            CF_MEJEPA_Q4_REASONING_LABELS,
            "CF_MEJEPA_Q4_REASONING_LABELS"
        );
        assert_eq!(
            CF_MEJEPA_Q4_PASS_ANNOTATIONS,
            "CF_MEJEPA_Q4_PASS_ANNOTATIONS"
        );
        assert_eq!(CF_MEJEPA_HEAD_CALIBRATIONS, "CF_MEJEPA_HEAD_CALIBRATIONS");
        assert_eq!(
            CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE,
            "CF_MEJEPA_THRESHOLD_CALIBRATION_PROVENANCE"
        );
        assert_eq!(CF_MEJEPA_PATHWAY_TREES, "CF_MEJEPA_PATHWAY_TREES");
        assert_eq!(CF_MEJEPA_SURFACED_PATHWAYS, "CF_MEJEPA_SURFACED_PATHWAYS");
        assert_eq!(
            CF_MEJEPA_OPERATOR_PATHWAY_CHOICES,
            "CF_MEJEPA_OPERATOR_PATHWAY_CHOICES"
        );
        assert_eq!(
            CF_MEJEPA_DOCKER_OUTCOME_LABELS,
            "CF_MEJEPA_DOCKER_OUTCOME_LABELS"
        );
        assert_eq!(
            CF_MEJEPA_CONTRADICTION_THRESHOLDS,
            "CF_MEJEPA_CONTRADICTION_THRESHOLDS"
        );
        assert_eq!(
            CF_MEJEPA_CONSTELLATION_PATTERNS,
            "CF_MEJEPA_CONSTELLATION_PATTERNS"
        );
        assert_eq!(
            CF_MEJEPA_CONNECTOME_TOPOLOGY_FEATURES,
            "CF_MEJEPA_CONNECTOME_TOPOLOGY_FEATURES"
        );
        assert_eq!(
            CF_MEJEPA_ACCEPTED_LABEL_REGISTRY,
            "CF_MEJEPA_ACCEPTED_LABEL_REGISTRY"
        );
        assert_eq!(
            CF_MEJEPA_LABEL_USEFULNESS_METRICS,
            "CF_MEJEPA_LABEL_USEFULNESS_METRICS"
        );
        assert_eq!(
            CF_MEJEPA_FAILURE_EVIDENCE_SETS,
            "CF_MEJEPA_FAILURE_EVIDENCE_SETS"
        );
        assert_eq!(
            CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP,
            "CF_MEJEPA_CHUNK_SKILL_MEMBERSHIP"
        );
        assert_eq!(
            CF_MEJEPA_SKILL_REVERSE_INDEX,
            "CF_MEJEPA_SKILL_REVERSE_INDEX"
        );
        assert_eq!(
            CF_MEJEPA_SKILL_LIFECYCLE_AUDIT,
            "CF_MEJEPA_SKILL_LIFECYCLE_AUDIT"
        );
        assert_eq!(CF_MEJEPA_MISTAKE_LOG, "CF_MEJEPA_MISTAKE_LOG");
        assert_eq!(
            CF_MEJEPA_MISTAKE_REPLAY_PRIORITY,
            "CF_MEJEPA_MISTAKE_REPLAY_PRIORITY"
        );
        assert_eq!(CF_MEJEPA_ONLINE_HEAD_STATE, "CF_MEJEPA_ONLINE_HEAD_STATE");
        assert_eq!(CF_MEJEPA_COVERAGE_SIGNALS, "CF_MEJEPA_COVERAGE_SIGNALS");
        assert_eq!(CF_MEJEPA_COMPLEXITY_SIGNALS, "CF_MEJEPA_COMPLEXITY_SIGNALS");
        assert_eq!(CF_MEJEPA_CHURN_SIGNALS, "CF_MEJEPA_CHURN_SIGNALS");
        assert_eq!(
            CF_MEJEPA_DOC_COVERAGE_SIGNALS,
            "CF_MEJEPA_DOC_COVERAGE_SIGNALS"
        );
        assert_eq!(CF_MEJEPA_DEP_CVE_SIGNALS, "CF_MEJEPA_DEP_CVE_SIGNALS");
        assert_eq!(CF_MEJEPA_TYPE_GRAPH_SIGNALS, "CF_MEJEPA_TYPE_GRAPH_SIGNALS");
        assert_eq!(CF_MEJEPA_TELEMETRY_SIGNALS, "CF_MEJEPA_TELEMETRY_SIGNALS");
        assert_eq!(
            CF_MEJEPA_LIVE_SESSION_SIGNALS,
            "CF_MEJEPA_LIVE_SESSION_SIGNALS"
        );
        assert_eq!(CF_MEJEPA_REDACTION_LOG, "CF_MEJEPA_REDACTION_LOG");
        assert_eq!(CF_MEJEPA_SIGNAL_DROP_LOG, "CF_MEJEPA_SIGNAL_DROP_LOG");
        assert_eq!(CF_MEJEPA_REPLAY_BUFFER, "CF_MEJEPA_REPLAY_BUFFER");
        assert_eq!(CF_MEJEPA_OOD_HARVEST, "CF_MEJEPA_OOD_HARVEST");
        assert_eq!(CF_MEJEPA_OOD_CALIBRATIONS, "CF_MEJEPA_OOD_CALIBRATIONS");
        assert_eq!(
            CF_MEJEPA_ONTOLOGY_GROWTH_AUDIT,
            "CF_MEJEPA_ONTOLOGY_GROWTH_AUDIT"
        );
        assert_eq!(CF_MEJEPA_MINCUT_REPORTS, "CF_MEJEPA_MINCUT_REPORTS");
        assert_eq!(CF_MEJEPA_PAIRWISE_MI, "CF_MEJEPA_PAIRWISE_MI");
        assert_eq!(
            CF_MEJEPA_INSTRUMENT_PROPOSALS,
            "CF_MEJEPA_INSTRUMENT_PROPOSALS"
        );
        assert_eq!(CF_MEJEPA_EMBEDDER_PROPOSALS, "CF_MEJEPA_EMBEDDER_PROPOSALS");
        assert_eq!(
            CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS,
            "CF_MEJEPA_EMBEDDER_PROPOSAL_REJECTIONS"
        );
        assert_eq!(
            CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY,
            "CF_MEJEPA_DYNAMIC_EMBEDDER_REGISTRY"
        );
        assert_eq!(
            CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE,
            "CF_MEJEPA_DYNAMIC_EMBEDDER_PROVENANCE"
        );
        assert_eq!(CF_MEJEPA_PLASTICITY_HISTORY, "CF_MEJEPA_PLASTICITY_HISTORY");
        assert_eq!(
            CF_MEJEPA_EMBEDDER_DEPENDENCY_GRAPH,
            "CF_MEJEPA_EMBEDDER_DEPENDENCY_GRAPH"
        );
        assert_eq!(
            CF_MEJEPA_EMBEDDER_FOUNDATIONALITY,
            "CF_MEJEPA_EMBEDDER_FOUNDATIONALITY"
        );
    }

    #[test]
    fn fingerprint_cfs_are_registered_in_daemon_opener() {
        let names = all_hygiene_referenced_cfs();
        for cf in FINGERPRINT_CFS {
            assert!(
                names.contains(cf),
                "fingerprint CF {cf} missing from daemon opener; seed catalog writes would miss the source-of-truth column family.",
            );
        }
    }

    #[test]
    fn fingerprint_cf_names_match_const_idents() {
        assert_eq!(
            CF_MEJEPA_FAILURE_FINGERPRINTS,
            "CF_MEJEPA_FAILURE_FINGERPRINTS"
        );
        assert_eq!(
            CF_MEJEPA_FINGERPRINT_REFERENCES,
            "CF_MEJEPA_FINGERPRINT_REFERENCES"
        );
        assert_eq!(
            CF_MEJEPA_FINGERPRINT_REVERSE_INDEX,
            "CF_MEJEPA_FINGERPRINT_REVERSE_INDEX"
        );
        assert_eq!(
            CF_MEJEPA_FINGERPRINT_CALIBRATION,
            "CF_MEJEPA_FINGERPRINT_CALIBRATION"
        );
        assert_eq!(CF_MEJEPA_FINGERPRINT_AUDIT, "CF_MEJEPA_FINGERPRINT_AUDIT");
        assert_eq!(
            CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS,
            "CF_MEJEPA_FINGERPRINT_SHIP_GATE_WINDOWS"
        );
        assert_eq!(CF_MEJEPA_FINGERPRINT_FISHER, "CF_MEJEPA_FINGERPRINT_FISHER");
        assert_eq!(
            CF_MEJEPA_FINGERPRINT_DORMANCY,
            "CF_MEJEPA_FINGERPRINT_DORMANCY"
        );
        assert_eq!(CF_MEJEPA_ADVERSARIAL_CORPUS, "CF_MEJEPA_ADVERSARIAL_CORPUS");
    }

    #[test]
    fn fingerprint_fisher_and_dormancy_cfs_are_registered_in_daemon_opener() {
        // TASK-FP-008 — both new CFs must land on the daemon opener slice or
        // the fingerprint stability snapshots will be silently dropped at
        // production runtime.
        let names = all_hygiene_referenced_cfs();
        assert!(
            names.contains(&CF_MEJEPA_FINGERPRINT_FISHER),
            "CF_MEJEPA_FINGERPRINT_FISHER missing from daemon opener; per-fingerprint EWC Fisher rows would not persist."
        );
        assert!(
            names.contains(&CF_MEJEPA_FINGERPRINT_DORMANCY),
            "CF_MEJEPA_FINGERPRINT_DORMANCY missing from daemon opener; per-fingerprint CBP dormancy rows would not persist."
        );
        // Also confirm the FINGERPRINT_CFS group is the single canonical list.
        assert!(FINGERPRINT_CFS.contains(&CF_MEJEPA_FINGERPRINT_FISHER));
        assert!(FINGERPRINT_CFS.contains(&CF_MEJEPA_FINGERPRINT_DORMANCY));
    }

    #[test]
    fn adversarial_cfs_are_registered_in_daemon_opener() {
        let names = all_hygiene_referenced_cfs();
        for cf in ADVERSARIAL_CFS {
            assert!(
                names.contains(cf),
                "adversarial CF {cf} missing from daemon opener; TASK-PY-G-060 rows would not persist.",
            );
        }
    }

    #[test]
    fn ood_harvest_cfs_are_registered_in_daemon_opener() {
        let names = all_hygiene_referenced_cfs();
        for cf in OOD_HARVEST_CFS {
            assert!(
                names.contains(cf),
                "OOD harvest CF {cf} missing from daemon opener; TASK-PY-G-057 rows would not persist.",
            );
        }
    }

    #[test]
    fn threshold_calibration_cfs_are_registered_in_daemon_opener() {
        let names = all_hygiene_referenced_cfs();
        for cf in THRESHOLD_CALIBRATION_CFS {
            assert!(
                names.contains(cf),
                "threshold calibration CF {cf} missing from daemon opener; TASK-PY-G-113 rows would not persist.",
            );
        }
    }

    #[test]
    fn reward_signal_cfs_are_registered_in_daemon_opener() {
        let names = all_hygiene_referenced_cfs();
        for cf in REWARD_SIGNAL_CFS {
            assert!(
                names.contains(cf),
                "reward signal CF {cf} missing from daemon opener; TASK-RWD-209 rows would not persist.",
            );
        }
    }

    #[test]
    fn tct_cfs_are_registered_in_daemon_opener() {
        let names = all_hygiene_referenced_cfs();
        for cf in TCT_CFS {
            assert!(
                names.contains(cf),
                "TCT CF {cf} missing from daemon opener; production TCT source-of-truth reads would miss persisted rows.",
            );
        }
    }
}
